### ISSUE TITLE
get_single_transaction failing for block 0

### ISSUE THREAD

**Issue by shivaenigma** [priestc/moneywagon#10]
- Try get_single_transaction with 4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b

These is due to the fact that both blockr and insight.bitpay somehow don't like this transaction.  blockchain.info shows this, but doesn't seem to have implemented get_single_transaction

**Comment by priestc** [comment]
Actually a lot of services do not support block 0 it seems. Some of them are due to moneywagon bugs, some of them are the service itself do not support block 0. Best that can be done is make non-working services raise `SkipThisService` when block 0 is invoked for those services...
